language: julia
julia:
  - nightly
  - 0.4
os:
  - linux
notifications:
  email: false
after_success:
- julia -e 'cd(Pkg.dir("LIBSVM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
